blueprint:
  name: Switch - Turn ON & OFF Entities
  description: "# \U0001F51B Switch - Turn ON & OFF Entities\n**Version: 1.5**\n\n\U0001F500
    One switch to rule them all - synchronize your entities effortlessly!\n\n**If
    you like my blueprints, and would like to show your support or just say thank
    you?** [Click Here](https://www.paypal.com/donate/?hosted_button_id=WAZS3QSDTPGA8)
    \U0001F642\n\n<details> <summary><b>The Automation Process:</b> \U0001F448</summary>\n\n
    \ - The Switch input can be any entity with an ON / OFF state (for example: lights,
    switches, helpers, WLED segments, scripts, or virtual toggles).\n  - When any
    Switch turns ON, the Main Entity is turned ON.\n  - When all Switches turn OFF,
    the Main Entity is turned OFF, optionally after a configurable Time Delay OFF.\n
    \ - If a Time Delay OFF is configured, the Main Entity remains ON for the specified
    duration after all Switches turn OFF.\n\n\n  - An optional Alternating Entity
    can be configured:\n    - When the Main Entity turns ON, the Alternating Entity
    turns OFF\n    - When the Main Entity turns OFF, the Alternating Entity turns
    ON\n    - If a Time Delay OFF is used, the Alternating Entity follows the same
    delay timing.\n\n\n</details>\n\nNeed help? \n- FAQ: [Click Here](https://community.home-assistant.io/t/481546/2)\n-
    Community Support Including Updates: [Click Here](https://community.home-assistant.io/t/481546)\n\nRequired
    = *\n"
  domain: automation
  input:
    switch:
      name: Switch *
      description: 'The switch or switches that control the main and alternating entities.
        The automation reacts when these change state.

        '
      selector:
        entity:
          multiple: true
          reorder: false
    main_entity:
      name: Main Entity *
      description: 'The entity or entities that will turn ON when any switch turns
        ON, and turn OFF only when all selected switches are OFF.

        '
      selector:
        entity:
          multiple: true
          reorder: false
    main_entity_time_delay_off:
      name: Main Entity - Time Delay OFF
      description: 'Sets how long the **Main Entity** remains ON after all **Switches**
        turn OFF. This delay will also affect the **Alternating Entity**, if configured,
        when it is turned ON.


        **Use case:** When controlling an LED transformer, this delay allows connected
        lights time to smoothly transition OFF before the transformer is powered down.
        It also helps keep the transformer ON briefly in case the lights turn back
        ON, preventing rapid ON/OFF cycling.

        '
      default: 0
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: minutes
          mode: slider
    alternating_entity:
      name: Alternating Entity (optional)
      description: 'Optional entity or entities that will always be in the opposite
        state of the main entity. Leave empty if not needed.

        '
      default: []
      selector:
        entity:
          multiple: true
          reorder: false
  source_url: https://gist.github.com/Blackshome/dbcd8ebfdd0350144fc1503fc0fa8112
mode: restart
max_exceeded: silent
variables:
  switch: !input switch
  main_entity: !input main_entity
  main_entity_time_delay_off: !input main_entity_time_delay_off
  alternating_entity: !input alternating_entity
  main_entities_off: '{{ expand(main_entity) | selectattr(''state'',''eq'',''off'')
    | map(attribute=''entity_id'') | list | default([]) }}

    '
  alternating_entities_on: '{{ expand(alternating_entity) | selectattr(''state'',''eq'',''on'')
    | map(attribute=''entity_id'') | list | default([]) }}

    '
triggers:
- trigger: state
  id: t0
  entity_id: !input switch
  from: 'off'
  to: 'on'
- trigger: state
  id: t1
  entity_id: !input switch
  from: 'on'
  to: 'off'
  for:
    milliseconds: 200
condition:
- condition: or
  conditions:
  - condition: and
    conditions:
    - condition: trigger
      id: t0
  - condition: and
    conditions:
    - condition: trigger
      id: t1
    - condition: state
      entity_id: !input switch
      state: 'off'
actions:
- choose:
  - alias: No alternating entities
    conditions:
    - condition: template
      value_template: '{{ alternating_entity == [] }}'
    sequence:
    - choose:
      - alias: Trigger ON (t0)
        conditions:
        - condition: template
          value_template: '{{ trigger.id == ''t0'' }}'
        sequence:
        - alias: Turn ON main entities
          if:
          - condition: template
            value_template: '{{ main_entities_off | length > 0 }}'
          then:
          - action: homeassistant.turn_on
            target:
              entity_id: '{{ main_entities_off }}'
      - alias: Trigger OFF (t1)
        conditions:
        - condition: template
          value_template: '{{ trigger.id == ''t1'' }}'
        sequence:
        - alias: Wait the number of minutes set in the ain enety time delay off
          delay:
            minutes: !input main_entity_time_delay_off
        - alias: Turn OFF main entities
          action: homeassistant.turn_off
          target:
            entity_id: !input main_entity
  - alias: With alternating entities
    conditions:
    - condition: template
      value_template: '{{ alternating_entity != [] }}'
    sequence:
    - choose:
      - alias: Trigger ON (t0)
        conditions:
        - condition: template
          value_template: '{{ trigger.id == ''t0'' }}'
        sequence:
        - alias: Turn ON main entities
          if:
          - condition: template
            value_template: '{{ main_entities_off | length > 0 }}'
          then:
          - action: homeassistant.turn_on
            target:
              entity_id: '{{ main_entities_off }}'
        - alias: Turn OFF alternating entities
          if:
          - condition: template
            value_template: '{{ alternating_entities_on | length > 0 }}'
          then:
          - action: homeassistant.turn_off
            target:
              entity_id: '{{ alternating_entities_on }}'
      - alias: Trigger OFF (t1)
        conditions:
        - condition: template
          value_template: '{{ trigger.id == ''t1'' }}'
        sequence:
        - alias: Wait the number of minutes set in the ain enety time delay off
          delay:
            minutes: !input main_entity_time_delay_off
        - alias: Turn OFF main entities
          action: homeassistant.turn_off
          target:
            entity_id: !input main_entity
        - alias: Turn ON alternating entities
          action: homeassistant.turn_on
          target:
            entity_id: !input alternating_entity
